[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
    skipPatterns = ["https://cdn.simpleicons.org"] 

[[plugins]]
  package = "netlify-plugin-inline-critical-css"
  
  [plugins.inputs]
    fileFilter = ["*.html"]
    directoryFilter = ["!node_modules"]
    dimensions = [
      { width = 414, height = 896 },  # Mobile
      { width = 1920, height = 1080 } # Desktop
    ] 